In [1]:
from pymongo import MongoClient
import pandas as pd

In [2]:
# Make connection
# Retrieve hostname, port, and database information about mongodb
# for mongolab, go to the dashboard, for e.g. https://mongolab.com/databases/minuku

mongodbURI = "mongodb://minuku:minuku@ds041871.mongolab.com:41871/minuku"
DB_NAME = "minuku"

In [3]:
try:
    client = MongoClient(mongodbURI)
    #use the test database
    db = client[DB_NAME]
except Exception as e:
    print "Mongo connection error %s"%e

In [4]:
# print all collections names
db.collection_names()

[u'backgroundlogging',
 u'ios-locations',
 u'isalive',
 u'session',
 u'system.indexes']

### Which devices are alive?

In [11]:
results = [x for x in db.isalive.find()]

In [13]:
results
pd.DataFrame(results)

,_id,city,device1,device_id,deviceid,timestamp,user_id
0,56ba78bee4b0a81ce40a1161,NaN,NaN,NaN,some1,NaN,NaN
1,56ba795de4b0a81ce40a1795,NaN,NaN,NaN,some1,NaN,NaN
2,56bb6137e4b0bb0889137077,NaN,alive,NaN,NaN,NaN,NaN
3,56bbf3ece4b0a81ce41b344d,Palo Alto,NaN,NaN,NaN,NaN,NaN
4,56bbf3f6e4b0bb08891a278e,Portola Valley,NaN,NaN,NaN,NaN,NaN
5,56bd2e09e4b0bb088928018d,NaN,NaN,359904058886102,NaN,2016-02-11 19:57:04 -0500,Minuku-928175401
6,56bd2e2ce4b0bb08892802c2,NaN,NaN,359904058886102,NaN,2016-02-11 19:57:39 -0500,Minuku-928175401
7,56bd2e53e4b0a81ce42a3462,NaN,NaN,359904058886102,NaN,2016-02-11 19:58:18 -0500,Minuku-928175401
8,56bd2e77e4b0bb0889280599,NaN,NaN,359904058886102,NaN,2016-02-11 19:58:54 -0500,Minuku-928175401
9,56bd2e9be4b0bb088928085f,NaN,NaN,359904058886102,NaN,2016-02-11 19:59:30 -0500,Minuku-928175401
10,56bd2ebfe4b0a81ce42a3999,NaN,NaN,359904058886102,NaN,2016-02-11 20:00:06 -0500,Minuku-928175401
11,56bd2ee5e4b0a81ce42a3b0e,NaN,NaN,359904058886102,NaN,2016-02-11 20:00:44 -0500,Minuku-928175401
12,56bd2f08e4b0a81ce42a3c55,NaN,NaN,359904058886102,NaN,2016-02-11 20:01:19 -0500,Minuku-928175401
13,56bd2f2ce4b0a81ce42a3dae,NaN,NaN,359904058886102,NaN,2016-02-11 20:01:55 -0500,Minuku-928175401
14,56bd2f50e4b0a81ce42a3f26,NaN,NaN,359904058886102,NaN,2016-02-11 20:02:31 -0500,Minuku-928175401
15,56bd2f74e4b0bb08892810bf,NaN,NaN,359904058886102,NaN,2016-02-11 20:03:07 -0500,Minuku-928175401
16,56bd2f99e4b0a81ce42a41f1,NaN,NaN,359904058886102,NaN,2016-02-11 20:03:44 -0500,Minuku-928175401
17,56bd2fbde4b0bb0889281349,NaN,NaN,359904058886102,NaN,2016-02-11 20:04:20 -0500,Minuku-928175401
18,56bd32fee4b0a81ce42ab352,NaN,NaN,359904058886102,NaN,2016-02-11 20:18:13 -0500,Minuku-928175401
19,56bd3565e4b0bb0889284d46,NaN,NaN,359904058886102,NaN,2016-02-11 20:28:28 -0500,Minuku-928175401
20,56bd37cfe4b0bb088928651c,NaN,NaN,359904058886102,NaN,2016-02-11 20:38:46 -0500,Minuku-928175401
21,56bd3a36e4b0a81ce42b00d4,NaN,NaN,359904058886102,NaN,2016-02-11 20:49:01 -0500,Minuku-928175401
22,56bd3ca0e4b0a81ce42b1a41,NaN,NaN,359904058886102,NaN,2016-02-11 20:59:18 -0500,Minuku-928175401
23,56bd3f08e4b0bb088928afa6,NaN,NaN,359904058886102,NaN,2016-02-11 21:09:35 -0500,Minuku-928175401
24,56bd4178e4b0a81ce42b9d8e,NaN,NaN,359904058886102,NaN,2016-02-11 21:19:59 -0500,Minuku-928175401
25,56bd43dfe4b0bb088928e22c,NaN,NaN,359904058886102,NaN,2016-02-11 21:30:14 -0500,Minuku-928175401
26,56bd464fe4b0bb088928fa76,NaN,NaN,359904058886102,NaN,2016-02-11 21:40:38 -0500,Minuku-928175401
27,56bd48b7e4b0bb0889290f5e,NaN,NaN,359904058886102,NaN,2016-02-11 21:50:53 -0500,Minuku-928175401
28,56bd4b20e4b0bb08892928ed,NaN,NaN,359904058886102,NaN,2016-02-11 22:01:11 -0500,Minuku-928175401
29,56bd4d87e4b0a81ce42c6aa3,NaN,NaN,359904058886102,NaN,2016-02-11 22:11:26 -0500,Minuku-928175401
30,56bd4ff1e4b0bb08892959e0,NaN,NaN,359904058886102,NaN,2016-02-11 22:21:43 -0500,Minuku-928175401
31,56bd5291e4b0a81ce42c9e7d,NaN,NaN,359904058886102,NaN,2016-02-11 22:32:56 -0500,Minuku-928175401
32,56bd553be4b0bb0889298f1f,NaN,NaN,359904058886102,NaN,2016-02-11 22:44:17 -0500,Minuku-928175401
33,56bd5867e4b0a81ce42cdabc,NaN,NaN,359904058886102,NaN,2016-02-11 22:57:50 -0500,Minuku-928175401
34,56bd68e1e4b0bb08892a9edf,NaN,NaN,359904058886102,NaN,2016-02-12 00:08:08 -0500,Minuku-928175401
35,56bd79b1e4b0a81ce42e8f64,NaN,NaN,359904058886102,NaN,2016-02-12 01:19:52 -0500,Minuku-928175401
36,56bd8b03e4b0a81ce42f4d73,NaN,NaN,359904058886102,NaN,2016-02-12 02:33:46 -0500,Minuku-928175401
37,56bd9ca0e4b0bb08892c2905,NaN,NaN,359904058886102,NaN,2016-02-12 03:48:55 -0500,Minuku-928175401
38,56bdae97e4b0bb08892c6bb9,NaN,NaN,359904058886102,NaN,2016-02-12 05:05:34 -0500,Minuku-928175401
39,56bdbf29e4b0a81ce430d890,NaN,NaN,359904058886102,NaN,2016-02-12 06:16:14 -0500,Minuku-928175401
40,56bdcf78e4b0bb08892d808f,NaN,NaN,359904058886102,NaN,2016-02-12 07:25:51 -0500,Minuku-928175401
41,56bddf4ae4b0bb08892e4c6c,NaN,NaN,359904058886102,NaN,2016-02-12 08:33:21 -0500,Minuku-928175401
42,56bde32ee4b0bb08892ebe48,NaN,NaN,359904058886102,NaN,2016-02-12 08:49:57 -0500,Minuku-928175401
43,56bde614e4b0bb08892ed809,NaN,NaN,359904058886102,NaN,2016-02-12 09:02:18 -0500,Minuku-928175401
44,56bdef99e4b0bb08892f2fc7,NaN,NaN,359904058886102,NaN,2016-02-12 09:42:56 -0500,Minuku-928175401
45,56bdf579e4b0bb08892f6349,NaN,NaN,359904058886102,NaN,2016-02-12 10:08:00 -0500,Minuku-928175401
46,56bdf8b2e4b0bb08892f80e2,NaN,NaN,359904058886102,NaN,2016-02-12 10:21:45 -0500,Minuku-928175401
47,56bdff16e4b0bb08892fbada,NaN,NaN,359904058886102,NaN,2016-02-12 10:49:00 -0500,Minuku-928175401
48,56be0528e4b0a81ce4340aa8,NaN,NaN,359904058886102,NaN,2016-02-12 11:14:54 -0500,Minuku-928175401
49,56be0b1be4b0a81ce434956b,NaN,NaN,359904058886102,NaN,2016-02-12 11:40:18 -0500,Minuku-928175401
50,56be117ce4b0bb0889306c96,NaN,NaN,359904058886102,NaN,2016-02-12 12:07:30 -0500,Minuku-928175401
51,56be179fe4b0bb088930f7a8,NaN,NaN,359904058886102,NaN,2016-02-12 12:33:41 -0500,Minuku-928175401
52,56be1dabe4b0bb0889313540,NaN,NaN,359904058886102,NaN,2016-02-12 12:59:29 -0500,Minuku-928175401
53,56be211de4b0a81ce4356f6a,NaN,NaN,359904058886102,NaN,2016-02-12 13:14:12 -0500,Minuku-928175401
54,56be27d9e4b0a81ce43603ea,NaN,NaN,359904058886102,NaN,2016-02-12 13:42:55 -0500,Minuku-928175401
55,56be35c0e4b0bb08893220ec,NaN,NaN,359904058886102,NaN,2016-02-12 14:42:15 -0500,Minuku-928175401
56,56be3983e4b0bb088932468c,NaN,NaN,359904058886102,NaN,2016-02-12 14:58:18 -0500,Minuku-928175401
57,56be3c27e4b0bb08893262f7,NaN,NaN,359904058886102,NaN,2016-02-12 15:09:34 -0500,Minuku-928175401